import type { Metadata } from 'next'
import './globals.css'
import { DarkModeProvider } from "@/app/context/DarkModeContext";
import { Layout } from "@/components/Layout/Layout";

export const metadata: Metadata = {
  title: 'Portfólio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Coloque o DarkModeProvider apenas onde for necessário */}
        <DarkModeProvider>
          <Layout>{children}</Layout>
        </DarkModeProvider>
      </body>
    </html>
  );
}
